[package]
name = "bob"
version = "0.1.0"
authors = ["geek <wpreul@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http-types = "1.0.1"
